### ISSUE TITLE
为什么突然一直报这个错误？

### ISSUE THREAD

**Issue by cooper360** [Grt1228/chatgpt-steam-output#23]
OkHttp-------->:<-- HTTP FAILED: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

之前一直运行没问题，这几天一直报错如上。
但是部署到服务器上就能正常运行，多台设备clone后运行都报同样问题，怪了。求解~（代码已经更新到git上同步最新的了还是会存在这个问题）
![image](https://user-images.githubusercontent.com/6768070/232527685-18677d1a-d268-4a4a-8039-f0ff5059c5a0.png)

**Comment by Grt1228** [comment]
> OkHttp-------->:<-- HTTP FAILED: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
> 
> 之前一直运行没问题，这几天一直报错如上。 但是部署到服务器上就能正常运行，多台设备clone后运行都报同样问题，怪了。求解~（代码已经更新到git上同步最新的了还是会存在这个问题） ![image](https://user-images.githubusercontent.com/6768070/232527685-18677d1a-d268-4a4a-8039-f0ff5059c5a0.png)

换节点试试

**Comment by cooper360** [comment]
解决了，节点不稳定，感谢感谢，排查了好久，终于找到问题了

**Comment by cooper360** [comment]
> > OkHttp-------->:<-- HTTP FAILED: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
> > 之前一直运行没问题，这几天一直报错如上。 但是部署到服务器上就能正常运行，多台设备clone后运行都报同样问题，怪了。求解~（代码已经更新到git上同步最新的了还是会存在这个问题） ![image](https://user-images.githubusercontent.com/6768070/232527685-18677d1a-d268-4a4a-8039-f0ff5059c5a0.png)
> 
> 换节点试试

解决了，节点不稳定，感谢感谢，排查了好久，终于找到问题了
