### ISSUE TITLE
流式问答如何做上下文关联，要关联AI的回答

### ISSUE THREAD

**Issue by niray** [Grt1228/chatgpt-steam-output#6]
流式问答如何做上下文关联，要关联AI的回答？

**Comment by Grt1228** [comment]
项目支持上下文关联，默认保持连接5分钟，默认上下文保持10个，5分钟无请求上下文会话销毁。
可以自己修改代码，我这个只是个简单的示例项目。可以看下代码：
https://github.com/Grt1228/chatgpt-steam-output/blob/main/src/main/java/com/unfbx/chatgptsteamoutput/controller/ChatController.java

**Comment by niray** [comment]
感谢回答，看见这段代码了，但是这只记录了用户提问的问题，并没有记载AI的回答，所以上下文的效果不好，我想问的是如何记录EventSource生成的回答在Cache中

**Comment by Grt1228** [comment]
> 感谢回答，看见这段代码了，但是这只记录了用户提问的问题，并没有记载AI的回答，所以上下文的效果不好，我想问的是如何记录EventSource生成的回答在Cache中

在linster中自己实现下
