### ISSUE TITLE
我更换了key和host，并使用梯子，但是web依旧会报错

### ISSUE THREAD

**Issue by futaotao0981** [Grt1228/chatgpt-steam-output#9]
![image](https://user-images.githubusercontent.com/127937334/225259313-03b53675-b775-4db7-8bb2-fbbe9ae24d83.png)
![image](https://user-images.githubusercontent.com/127937334/225259547-03a9a4e0-14f7-40b2-a23d-3c25930ddcab.png)

**Comment by Grt1228** [comment]
使用梯子，要在程序里设置程序代理。
推荐使用代理的host：https://github.com/noobnooc/noobnooc/discussions/9

**Comment by Grt1228** [comment]
如果没有使用代理host
那需要在代码中进行代理

**Comment by xiaowangsmile** [comment]
我也出现类问题，在chatgpt-java-main这个测试类里面是正常可以输出的 但是搞到这个项目里面就报错

**Comment by hc1379321759** [comment]
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/48503029/227902309-27f19019-cced-4c7a-a7f7-49074f6a58dd.png">
这边第一个请求delta里只有 role, 第二个只有 content，但是 Message 中需要两个参数都不为 null，所有 web 就报错了

**Comment by Grt1228** [comment]
> <img alt="image" width="1306" src="https://user-images.githubusercontent.com/48503029/227902309-27f19019-cced-4c7a-a7f7-49074f6a58dd.png">
> 
> 这边第一个请求delta里只有 role, 第二个只有 content，但是 Message 中需要两个参数都不为 null，所有 web 就报错了

更新新版，已经支持。
